[project]
name = "triviagpt"
version = "0.1.0"
description = "Trivia game using ChatGPT as the trivia host"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-W ignore::DeprecationWarning"
testpaths = [
    "tests"
]