[default]

# DB and Redis config matches with docker-compose.yml file under local-dev/

DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "postgres"
DATABASE_NAME = "triviagpt"

REDIS_HOST = "localhost"
REDIS_PORT = 6379



[testing]

# Override database name when running tests

TESTING = true
DATABASE_NAME = "postgres"