version: '3'

services:
  # Run a redis and expose it on port 6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # Run a postgres database and expose it on port 5432
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres